[profile.default]
solc_version = "0.8.24"
evm_version = "cancun"

via_ir = true

optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/"
]

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://rpc.ankr.com/eth"
base = "https://rpc.ankr.com/base"
poly = "https://rpc.ankr.com/polygon"
opti = "https://rpc.ankr.com/optimism"
arbi = "https://rpc.ankr.com/arbitrum"

[etherscan]
arbitrum = {key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
sepolia = {key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }